### ISSUE TITLE
Hacktoberfest issue

### ISSUE THREAD

**Issue by dpnshusharma** [akanksha-raghav/Hacktoberfest2021#279]
My pull request got disqualified from hacktoberfest from this repository it says - This pull request was submitted to a repository that does not follow the values of Hacktoberfest, so has been excluded. No pull requests to this repository will be counted for Hacktoberfest.

**Comment by Mewwaa** [comment]
Damn, my PR got disqualified too. Guys, don't send pull requests to this repo 'cos they won't count into participant goals
